# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

  schedule:
    - cron: '42 14 * * *'  # Runs daily at  14:42 UTC

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Print current UTC time
      run: date -u

    - name: Dummy step
      run: echo "Testing the pipeline"
