# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#  push:
#    branches: [main]

  schedule:
    - cron: '45 20 * * *'  # Runs daily at  20:15 UTC

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Print current UTC time
      run: date -u

    - name: Dummy step
      run: echo "Testing the pipeline"

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout non-defualt branch
        uses: actions/checkout@v4
        with:
          ref: schedule

      - name: Check branch
        run: cat ./text.txt
